# Generated by Django 5.2 on 2025-06-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="flag_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
    ]
